name: flutter_app
description: A E-commerce Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons:
  get:
  chopper:
  google_sign_in:
  firebase_core:
  firebase_auth:
  sms_autofill:
  firebase_storage:
  flutter_facebook_login:
  cloud_firestore:
  splash_screen_view:
  shared_preferences:
  rating_bar:
  lottie:
  badges:
  carousel_slider:
  flutter_launcher_icons:
  bottom_bar_with_sheet:
  get_storage:
  image_picker:
  getwidget:
  url_launcher:
  flutter_svg:
  flutter_colorpicker:
  pin_entry_field:


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  chopper_generator:

flutter_icons:
  android: true
  ios: true
  image_path: "src/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - src/images/
    - src/json/
    - src/fonts/

  fonts:
   - family: Crimson
     fonts:
       - asset: src/fonts/font.ttf